[package]
name = "chip8-emulation"
version = "0.1.0"
authors = ["Matthew Neale Que <matthew.neale.que@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
